<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { AlertTriangle, BadgeCheck, Save } from 'lucide-vue-next'
import { isSupabaseConfigured, requireSupabase } from '../lib/supabase'

const profile = reactive({ id: '', tax_code: '', legal_entity_name: '', taxpayer_type: 'household_business', calculation_mode: 'manual_review', effective_from: new Date().toISOString().slice(0, 10) })
const message = ref('')
const error = ref('')
async function load() { if (!isSupabaseConfigured) return; const { data, error: loadError } = await requireSupabase().from('tax_profiles').select('*').order('effective_from', { ascending: false }).limit(1).maybeSingle(); if (loadError) { error.value = loadError.message; return } if (data) Object.assign(profile, data) }
async function save() { if (!isSupabaseConfigured) { error.value = 'Chưa có cấu hình Supabase.'; return } const payload = { tax_code: profile.tax_code, legal_entity_name: profile.legal_entity_name, taxpayer_type: profile.taxpayer_type, calculation_mode: 'manual_review', effective_from: profile.effective_from, config: { reviewedAt: new Date().toISOString() } }; const client = requireSupabase(); const { error: saveError } = profile.id ? await client.from('tax_profiles').update(payload).eq('id', profile.id) : await client.from('tax_profiles').insert(payload); if (saveError) error.value = saveError.message; else message.value = 'Đã lưu hồ sơ thuế. Số thuế phải nộp vẫn cần kế toán/đại lý thuế phê duyệt.' }
onMounted(load)
</script>

<template>
  <div class="page-intro"><div><p class="eyebrow">Tuân thủ & kiểm toán</p><h2>Hồ sơ thuế và báo cáo doanh thu</h2><p>Hệ thống kết nối doanh thu/hóa đơn để chuẩn bị số liệu, nhưng không tự khai hoặc tự chốt nghĩa vụ thuế.</p></div></div><section class="legal-notice"><AlertTriangle :size="24" /><div><strong>Bắt buộc kiểm tra pháp lý trước khi nộp tờ khai</strong><p>Chế độ thuế phụ thuộc loại hình kinh doanh, doanh thu, hóa đơn và hồ sơ thực tế. Dữ liệu này dùng để quản trị và đối soát, không thay thế tư vấn thuế chuyên môn.</p></div></section><div class="tax-layout"><section class="panel form-panel"><h3>Hồ sơ người nộp thuế</h3><div class="form-grid"><label><span>Mã số thuế *</span><input v-model="profile.tax_code" placeholder="Nhập mã số thuế" /></label><label><span>Tên pháp lý *</span><input v-model="profile.legal_entity_name" placeholder="Tên hộ kinh doanh / doanh nghiệp" /></label><label><span>Loại hình</span><select v-model="profile.taxpayer_type"><option value="household_business">Hộ/cá nhân kinh doanh</option><option value="company">Doanh nghiệp</option></select></label><label><span>Hiệu lực từ</span><input v-model="profile.effective_from" type="date" /></label></div><p v-if="error" class="form-error">{{ error }}</p><p v-if="message" class="success-inline">{{ message }}</p><button class="primary-button" @click="save"><Save :size="18" /> Lưu hồ sơ thuế</button></section><section class="panel tax-checklist"><div class="panel-heading"><h3>Checklist tuân thủ</h3><BadgeCheck :size="21" /></div><ul><li>Đối soát hóa đơn đã thanh toán với doanh thu báo cáo.</li><li>Đối soát chi phí nhập kho và chi phí vận hành có chứng từ.</li><li>Rà soát hướng dẫn hiện hành trước mỗi kỳ khai/nộp thuế.</li><li>Lưu giữ invoice, payment và dữ liệu thuế; hệ thống không áp dụng quy tắc xóa 90 ngày cho nhóm này.</li></ul></section></div>
</template>
